
parse-server:
  volumes:
    - ./parse-server:/parse
  build: ./parse-server
  command: parse-server --cloud /parse/cloud/main.js
  ports:
    - "1337:1337"
  environment:
    PARSE_SERVER_DATABASE_URI: 'mongodb://192.168.99.100:27017/dev' # $PARSE_SERVER_DATABASE_URI
    PARSE_SERVER_APPLICATION_ID: 'myAppId' # $PARSE_SERVER_APPLICATION_ID
    PARSE_SERVER_MASTER_KEY: 'myMasterKey' # $PARSE_SERVER_MASTER_KEY
    PARSE_SERVER_URL: 'http://localhost:1337/parse' # $PARSE_SERVER_URL
    PARSE_SERVER_DATABASE_OPTIONS: $PARSE_SERVER_DATABASE_OPTIONS
    PORT: '1337'
    PARSE_SERVER_DATABASE_OPTIONS: $PARSE_SERVER_DATABASE_OPTIONS
    PARSE_SERVER_COLLECTION_PREFIX: $PARSE_SERVER_COLLECTION_PREFIX
    PARSE_PUBLIC_SERVER_URL: $PARSE_PUBLIC_SERVER_URL
    PARSE_SERVER_CLIENT_KEY: $PARSE_SERVER_CLIENT_KEY
    PARSE_SERVER_JAVASCRIPT_KEY: $PARSE_SERVER_JAVASCRIPT_KEY
    PARSE_SERVER_REST_API_KEY: $PARSE_SERVER_REST_API_KEY
    PARSE_SERVER_DOT_NET_KEY: $PARSE_SERVER_DOT_NET_KEY
    PARSE_SERVER_CLOUD_CODE_MAIN: $PARSE_SERVER_CLOUD_CODE_MAIN
    PARSE_SERVER_PUSH: $PARSE_SERVER_PUSH
    PARSE_SERVER_OAUTH_PROVIDERS: $PARSE_SERVER_OAUTH_PROVIDERS
    PARSE_SERVER_FILE_KEY: $PARSE_SERVER_FILE_KEY
    PARSE_SERVER_FACEBOOK_APP_IDS: $PARSE_SERVER_FACEBOOK_APP_IDS
    PARSE_SERVER_ENABLE_ANON_USERS: $PARSE_SERVER_ENABLE_ANON_USERS
    PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION: $PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION
    PARSE_SERVER_MOUNT_PATH: $PARSE_SERVER_MOUNT_PATH
    PARSE_SERVER_FILES_ADAPTER: $PARSE_SERVER_FILES_ADAPTER
    PARSE_SERVER_EMAIL_ADAPTER: $PARSE_SERVER_EMAIL_ADAPTER
    PARSE_SERVER_VERIFY_USER_EMAILS: $PARSE_SERVER_VERIFY_USER_EMAILS
    PARSE_SERVER_APP_NAME: $PARSE_SERVER_APP_NAME
    PARSE_SERVER_LOGGER_ADAPTER: $PARSE_SERVER_LOGGER_ADAPTER
    PARSE_SERVER_LIVE_QUERY_OPTIONS: $PARSE_SERVER_LIVE_QUERY_OPTIONS
    PARSE_SERVER_CUSTOM_PAGES: $PARSE_SERVER_CUSTOM_PAGES
    PARSE_SERVER_MAX_UPLOAD_SIZE: $PARSE_SERVER_MAX_UPLOAD_SIZE
    PARSE_SERVER_SESSION_LENGTH: $PARSE_SERVER_SESSION_LENGTH
  links:
    - mongo

parse-dashboard:
  command: parse-dashboard --config /dashboard/config.json --allowInsecureHTTP #--appId $APP_ID --masterKey $MASTER_KEY --port 4040 --serverURL $SERVER_URL --allowInsecureHTTP
  volumes:
    - ./dashboard:/dashboard
  links:
    - parse-server
  build: ./dashboard
  ports:
    - "4040:4040"

site:
  command: http-server /opt/site/public -p 80
  build: ./site
  volumes:
    - ./site:/opt/site
  ports:
    - "80:80"
  links:
    - parse-server

mongo:
  image: mongo:3
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false"
